### ISSUE TITLE
Document build process for IL2CPP platforms

### ISSUE THREAD

**Issue by ecmjohnson** [YarnSpinnerTool/YarnSpinner#141]
The use of Newtonsoft.Json makes it impossible to use JSON assets with YarnSpinner on ahead of time compilation (i.e. IL2CPP) platforms due to use of methods in the `System.Reflection.Emit` namespace in that library (see #135 and [this page](https://docs.unity3d.com/Manual/ScriptingRestrictions.html)).

Alternative libraries do exist that will work on ahead of time compilation platforms (e.g. [this Unity asset](https://www.assetstore.unity3d.com/#!/content/11347)) so this is not a technical limitation. I did see **mcjones** mentioned "something about it bumping the minimum supported .net version" and that might be a good reason not to use a different JSON parsing library.

It would be nice to have some documentation on how to build with IL2CPP or advising against using JSON on ahead of time compilation platforms

**Comment by stalhandske** [comment]
It's super awesome that the JSON file support was removed. Made things easier for building for IL2CPP.

According to this comment in the Slack (https://narrativegamedev.slack.com/archives/C5F1PEGER/p1513097494000527) the CsvHelper also uses reflection. I was able to switch it for a different one in order to build for IL2CPP.

For anyone with the same problem I used this one: https://www.codeproject.com/Tips/823670/Csharp-Light-and-Fast-CSV-Parser

**Comment by desplesda** [comment]
I just did a test build of the Space demo on macOS with IL2CPP, off the current `develop` branch, with no errors. Is this issue still present?

**Comment by ecmjohnson** [comment]
@desplesda Removing the JSON support as discussed in #173 and implemented in 20ed206 would have made this a non-issue for me when I used YarnSpinner since I would have just used yarn text files instead of JSON files. From my perspective, this issue is resolved
