### ISSUE TITLE
Options select automatically after choosing first option

### ISSUE THREAD

**Issue by LivKanyway** [YarnSpinnerTool/YarnSpinner#163]
After selecting an option for the first time in a scene, continuing by pressing keys will automatically select future options with the same index as the first option selected.

For instance, if you choose the first option (with a setoption index of 0), the next time you are presented with options, you can advance by pressing a key and it will automatically choose the option with the setoption index of 0. 
This happens for all subsequent option choices. If you select an option with a different index, then following options will auto-select to that new index.

RunOptions should remove this saved index after the option is selected.

**Comment by unknowndevice** [comment]
As far as I'm aware this is to do with how the UnityEngine.EventSystems handles Selectables. It retains the previously selected UI element because you haven't told it to deselect. So when the Options are SetActive for the next set of Options it remembers the last Selected.

If you want to prevent this from happening just call ```EventSystem.current.SetSelectedGameObject(null);``` where you handle the Options onClick/OnSubmit.

**Comment by McJones** [comment]
There hasn’t been any activity on this in a while so I am closing this issue.
If the issue reappears please open a new issue.
