### ISSUE TITLE
Going backwards in dialogue?

### ISSUE THREAD

**Issue by LivKanyway** [YarnSpinnerTool/YarnSpinner#172]
Working on a game and we were thinking to implement a way to move backwards one line at a time, just like RunLine moves the dialogue forward one line on click. (For instance, pressing the left arrow would display the previous line in the dialogue.)

Has anyone implemented this yet? Does anyone have any suggestions on how to implement this?

**Comment by McJones** [comment]
hmm that is a tricky one depending on what you are after.

If you are just after being able to view the previous lines of dialogue then the easiest way would be to have a Stack where each time you get a line back from YarnSpinner you would push that onto the stack.
Then when the user presses the left arrow you pop the value off the stack and show it.
Or if you need to keep them around indefinitely, you'd do the same thing but with a List instead of a stack and just run through the list from start to end as the user presses the left arrow.

If you want to be able to actually go back in time and run a line of dialogue again that is way trickier and I don't have any real idea where you'd begin in that.

**Comment by desplesda** [comment]
"Showing the last line that was sent by Yarn Spinner" is a different kind of problem to "execute the program in reverse" (which is _much_ more complex.) As @McJones says, this is something that's best handled in the game, by keeping a log of lines that were received, and displaying them. 

If we get lots of people asking for the ability to replay existing lines, we'll return to this, but for now I'm going to close this issue. Thank you for taking the time to request it, and thanks for using Yarn Spinner! :heart:

**Comment by awaredserver** [comment]
Hi. I'm using Gdevelop to make a linear visual novel based on a poem and I like to offer users a way to navigate backward as well. Didn't know this was so complicated. should I create another list in reverse and jump to the corresponding line?
