### ISSUE TITLE
Future of Yarn Spinner

### ISSUE THREAD

**Issue by McJones** [YarnSpinnerTool/YarnSpinner#183]
Hello everyone,

We've just pushed a new [markdown document](https://github.com/YarnSpinnerTool/YarnSpinner/blob/master/ROADMAP.md) showing our road map for what we think the future of Yarn Spinner should be.

We really, really want your feedback on that so please shout out any concerns, issues, or thoughts you might have here or in the Slack.

**Comment by fragmental** [comment]
Hello.
The main reason I chose yarnspinner over cradle(twine) is that cradle compiled the twine story file into bytecode, and I wanted something that could load the story files at runtime.  My goal was to allow people to create their own stories and add them after compilation.  I have a working implementation where I can just drop the yarn file into the folder and it automatically adds it when the program is run.  

Would these changes to generate bytecode, instead of parsing the yarn file every time, prevent me from doing this in the future?

Admittedly, there is  probably a better way for me to do this.  My initial thoughts have been something like a doom wad, or maybe something more comprehensive.  Additionally, I haven't actually made the project public so others could create their own stories, because I wanted to make some improvements first.  But it technically does work now.

**Comment by desplesda** [comment]
We plan to provide the Yarn Spinner compiler as a .DLL, which Unity games can embed and use for runtime compilation, if they want it.

**Comment by fragmental** [comment]
I'm not super familiar with this kind of stuff.  Would that be like Just-in-time (JIT) compilation?  Would that be secure?  I'm guessing that would allow it to outwardly work the way it does now, but would work differently behind the scenes.

Also, I added code that allows me to get the option names so that I can check if they've been visited.  #139 Would that still work?

With this being an open source project, I can always use an outdated fork if I have to, though that wouldn't be ideal.  There would be no good reason to hold up progress for the sake of my silly project.

My current implementation should probably be reworked before publishing anyway, because it doesn't have any way to check the yarn file for integrity, and just crashes if it sees something it doesn't like.  It was really just a proof of concept.

**Comment by desplesda** [comment]
Yeah, it works somewhat similarly to JIT, though it compiles to Yarn Spinner byte code rather than to CIL byte code or machine code. 

We don't provide any promises regarding security for Yarn Spinner, and at the time of writing it hasn't been audited for security issues. You should always be extremely suspicious of _any_ input that comes from the user!

Re: your question about being able to query for visited nodes: yes, if this breaks then we'll consider that to be a bug that needs fixing!

**Comment by giulianob** [comment]
Looks great. I'm using Yarn with Godot and its working well so far but loading the file is a bit slow so hopefully bytecode is faster.

**Comment by fragmental** [comment]
@desplesda I don't know if I was very clear about my question in regards to visited nodes.  Or perhaps I'm misunderstanding.  I was referring to the code in the pull request that I linked, #139, that is a modification to virtualmachine.cs to expose the option names of the nodes.  Since the pull request hasn't been accepted, I don't know why it not working would be considered a bug.

If virtual machine continues to function the same way, then I assume my modification will also.  If it doesn't, I can still use my outdated fork, though I think it would be better to stay in sync with upstream.  There's currently no conflicts with base branch.

**Comment by StefanJanssen95** [comment]
I just came across this and would like to help. Looking at the roadmap I see there is syntax highlighting for VS Code planned for V1.0. Has development of this already started or can people set it up to move the repo to this project?
I've made a syntax highlighter in VS code once with an even easier language. So this seems to me something I might be able to pick up and help out with.

**Comment by desplesda** [comment]
This is actually already live on the Marketplace! https://marketplace.visualstudio.com/items?itemName=SecretLab.yarn-spinner

The source code isn’t yet on GitHub, but I’ll be putting it up very soon. If you’re interested in helping out, I’d love your contributions!

**Comment by desplesda** [comment]
There's been some good discussion on this, and given that we're now past the 1.0 milestone, I'm going to go ahead and close this issue. Thanks to all who commented; here's to a bright future for Yarn Spinner.
