### ISSUE TITLE
Compact DialogueRunner class

### ISSUE THREAD

**Issue by Kicory** [YarnSpinnerTool/YarnSpinner#207]
Current DialogueRunner class should inherit from new 'DialogueRunner_base' class that only implements very core interfaces.
-
Current DialogueRunner class has many functionality, which is slightly too many for simple usage.
Command dispatching that uses GameObject.Find() is useful but I think there are many programmers who don't like that function... GameObject.Find() is one obvious example but there are some more functionalities that I decided to not use in my game.

Those functionalities are definitely useful, but should be customizable option for who don't need that. I think this improvement does not change current usage of DialogueRunner because it's just separating the class to two.

p.s. I wanted to make a pull request... but I'm kind of newbie to github. Sorry...

**Comment by Kicory** [comment]
Sorry, I accidentally pressed enter and empty issue was uploaded... I'll write more details soon.

**Comment by desplesda** [comment]
Command dispatching only uses `GameObject.Find` when using the `YarnCommand` attribute - the `AddCommandHandler` method lets you directly register a delegate to use. If you do your commands this way and never use `YarnCommand`, `GameObject.Find` is simply never used. 

I agree that the `DialogueRunner` is slightly too full of features, and breaking it out into some smaller files might be useful. I don't think that making `DialogueRunner` be a subclass of another, lighter class would be the best way to approach it, because I can't see a reason for there to be any sibling classes alongside `DialogueRunner`.

Feel free to make a pull request! I'd be delighted to review it!

**Comment by desplesda** [comment]
Closing this issue since the conversation here appears done! Please create a new issue if there's more to add!
