### ISSUE TITLE
Need Help with accessing the line hash of the current line

### ISSUE THREAD

**Issue by Ants-Aare** [YarnSpinnerTool/YarnSpinner#232]
Hello YarnSpinner Team,
We're an indie team working on a new game. I haven't seen anything on the page, but for us Voice over support would be fairly important.
I've been wondering if I could somehow get access to the "#line1234" hash kind of thing, while it's processing the line. I want to use these hashes to select audioclips from a dictionary/read them from the resources folder, but I can't get access to them right now. Is there any possibility to get that information about the current line or maybe even the next line, so that it can load it into Ram?

Thanks for taking the time. Really cool tool. It would be a bummer if we would need to use a different tool just because of this. 

Ants Aare

**Comment by desplesda** [comment]
Hi!

The `Line` data that the `DialogueUI`'s `RunLine` method receives contains the line's ID (the 'hash' you referred to). I'd suggest you make a copy of the `DialogueUI` class, and add the behaviour you want to have there.

(Also: voiceover support is currently being worked on, but we don't currently have a timeframe for that yet.)

Let me know if you need any more info, and thanks for using Yarn Spinner!

**Comment by Ants-Aare** [comment]
Thanks for the quick response. Line.id works perfectly. The dialogue system now runs with voiceover for us, but I don't know how it'll affect memory in the long run. Is there some way to get all line codes for the entire dialogue conversation when you start from a certain node? That way we can only load in what's going to be needed. Alternatively I thought about getting the code for the next line and loading te audioclip while the current one is being played. And if you're working on adding it natively I'd suggest adding an option to adapt the text speed depending on the length of the audio file. That worked really well for us. 

Thanks for making this tool open source, we definitely saved a lot of time and resources.

**Comment by desplesda** [comment]
There isn't currently a built-in way to get the list of all line codes in a node, but the string tables that Yarn Spinner for Unity generates for each Yarn file contains information on where each line was found. You could use that to make a list of all lines in a node. [More information on string tables is available on the Yarn Spinner site](https://yarnspinner.dev/docs/unity/localisation/#string-tables).

(This feature is something that we'll likely need to add in the future, in order to support better performance for voiceover.)

I'll close this issue now, since the main question appears to be resolved; if you need more help, please add to this thread or ask in the [Slack community](http://lab.to/narrativegamedev)!
