### ISSUE TITLE
Request for feedback: Split the Yarn Spinner repo into multiple repos

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#246]
Hi, all!

I'm planning to reorganise the repositories here on GitHub to make things easier for future project expansion.

The current repo layout of Yarn Spinner is entirely the result of historical accident, and not deliberate planning. The Yarn editor was the original project; when I began work on Yarn Spinner, it was as an independent project, so I created a stand-alone repo for it, and kept both the library and the Unity component in the same repo. After Alec, who owned the Yarn repo, passed away, we migrated it to this organisation and renamed it to Yarn Editor.

We now have five projects in four repos:

* [Yarn Editor](https://github.com/YarnSpinnerTool/YarnEditor)
* Yarn Spinner and Yarn Spinner for Unity (this repo)
* [Yarn Spinner Visual Studio Code extension](https://github.com/YarnSpinnerTool/VSCodeExtension)
* [Yarn Spinner documentation website](https://github.com/YarnSpinnerTool/Docs).

As more projects come online, we'll need a better structure, especially as we build out other dependent projects like the Unreal integration. Additionally, as we move to UPM package distribution of the  To that end, I'm planning on separating the Yarn Spinner for Unity material into its own repo.

Here's what I'm proposing we do for this repo.

* Create a new repo, called YarnSpinnerTool/YarnSpinner-Unity
* Migrate the contents of the Unity/Assets/ directory into it, ideally preserving history
* Yarn Spinner (the library) and Yarn Spinner for Unity will become separate projects, but will aim to maintain major and minor version number parity.
  * Major and minor version number changes on Yarn Spinner and Yarn Spinner for Unity will happen simultaneously.
  * Patch version number changes can happen independently.
* `.unitypackage` releases will be done from the Unity repo.
* Create a new repo for the command line tool, YarnSpinnerTool/YarnSpinnerConsole (specific name TBD.)
* Changelogs and release notes will be independently maintained on a per-project basis.

Questions:

* We're in the planning stages of an improved JavaScript implementation of Yarn Spinner, to bring bondage.js up to feature parity with the C# implementation. Should that live in this repo, or should it have its own?
  * If it should have its own, should the grammar files for Yarn Spinner be in a third repo? ("YarnSpinnerTool/YarnLanguage"?)
* @favoyang, currently the UPM package releases are done on the `upm` branch, which has a different folder structure. Does it make sense to do all of our UPM releases from the master branch of the new Unity repo?

Let me know what you think. I'd like to make a decision on this within the next week, so that we can do this before the v1.2 release.

**Comment by Schroedingers-Cat** [comment]
I like this a lot.

> Migrate the contents of the Unity/Assets/ directory into it, ideally preserving history

Easiest way I can think of would be to clone/fork this repo, rename it to YarnSpinner-Unity and delete all the rest from that repo. Then delete the unity project from this repo. This way, all commit references to issue discussions remain and the entire history is preserved.

It would be great if we could store the binaries of the yarn library directly in the DLL folder of the unity project.

I wouldn't mind having multiple implementations of the compiler in a single repo.

**Comment by unknowndevice** [comment]
Agree with breaking up the repos! Especially since there are other platforms like unreal coming down the line.

I see the javascript implement as just being another platform like unity, so in that case another repo makes sense to me! In that case it would probably make sense to have the grammer files in their own repo so they can be used with whatever platform as necessary.

Making the Yarn-Unity repo master be the UPM package release makes sense to me! Packages are the future of Unity and ultimately how everyone should be updating Yarn (since it's easier to update). So it makes sense to just have this as the master.

Another advantage of breaking up the repos is it'll potentially make it easier for people to contribute to a specific aspect of that project.

**Comment by favoyang** [comment]
> * Migrate the contents of the Unity/Assets/ directory into it, ideally preserving the history

`git subtree` is the tool to split part of your repository to a new branch or repository, while keeping all history.

If you still want to keep the .unitypackage thing, then you should make the `Unity/` path as the root of the new YarnSpinner-Unity repository. Because you still need a full Unity structure to do it.

If you want to only support UPM, then you should make the `Unity/Assets/YarnSpinner` path as the root of the new YarnSpinner-Unity repository.

There's one more thing for UPM support, as I did in [.github/workflows/upm.yml](https://github.com/YarnSpinnerTool/YarnSpinner/blob/74dcc685e02e2f7ec290b6a002a02895aa6da930/.github/workflows/upm.yml): to distribute DLLs (the library) with the UPM:
- It compiles DLL via CI
- It copies DLL meta files to DLL folder
- It moves the Samples folder according to a UPM convention.

Since you break down this repository, you have a few choices
- You can upload DLL directly to the YarnSpinner-Unity repository master branch, and sync it regularly.
- You can use CI to generate a UPM branch, by downloading the latest version of YarnSpinner-Core DLL (or source then compile to DLL), add to Git.
- You turn the YarnSpinner-Core a UPM, then let YarnSpinner-Unity package depends on YarnSpinner-Core package.

**Comment by desplesda** [comment]
Awesome. What I think we'll do is make the Unity repo root be what's currently at Assets/YarnSpinner, and make the repo itself be the UPM root. We'll use CI to sync the current `master` .DLL with the C# compiler repo.

This means we don't have to have branches with different folder structures; it also will help avoid the problem that we have right now, where users download the repo itself, open it in Unity, and don't understand why they're seeing errors. We already have to use CI to generate the .unitypackage anyway, so I don't see a problem with it.

Thanks for the excellent discussion, all. What I've decided to do is:

* We'll keep the compiler and the grammar sources in this repo, `YarnSpinnerTool/YarnSpinner`.
  * The platforms will be subfolders off the root of the compiler repo. Initially, there'll be just one - `csharp`.
* We'll split the `Unity/Assets/YarnSpinner` directory of this repo into its own repo, `YarnSpinnerTool/YarnSpinner-Unity`.
  * It will serve as the UPM repo, and we'll also generate `.unitypackage` builds from CI for it.
* We'll split the `YarnSpinnerConsole` directory of this repo into its own repo, `YarnSpinnerTool/YarnSpinnerConsole`.

I'll do this split after we get v1.2 out, which will be very soon - that way, we can start fresh with the repo while getting ready for the v2.0 changes.

**Comment by desplesda** [comment]
This has now been done. For future Yarn Spinner for Unity work, please see [YarnSpinnerTool/YarnSpinner-Unity](https://github.com/YarnSpinnerTool/YarnSpinner-Unity). Code for the Unity integration will be removed from this repo, and Unity-specific pull requests will be either closed or manually merged into the new repo by me. Unity-specific issues will be transferred to the new repo.

I'm closing this issue now, but if anyone has any questions, please post them here or open a new issue.

Thanks, all!
