### ISSUE TITLE
Proposal: Static Typing in Yarn Spinner 2.0

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#260]
## Rationale

Yarn Spinner currently has a dynamic type system. Variables in Yarn Spinner are permitted to take any type of value at any time, and may change their type over the course of the program's execution.

Dynamic type systems offer flexibility, but increase the possibility of run-time bugs caused by mis-matched types. They also make it harder for analysis tools to reason about the program.

As a result, instances of the `Value` class, which is the underlying storage class for variables, may be of any type at any time, and must have storage for all types, which wastes memory.

Yarn Spinner's variable system is frequently coupled with save-game systems. As a result of the dynamic type system, save game systems must also assume that any variable could be any type.

Finally, Yarn Spinner's type system provides for implicit type conversion, such as when a number is compared to a boolean. This requires that Yarn Spinner implement rules for how types are converted, and those rules may not necessarily be what the programmer expects.

In short, the flexibility offered by dynamic type systems is largely not necessary for the kinds of work that Yarn Spinner does, makes it easier for writers to make mistakes, and complicates the work of programmers and designers working with Yarn Spinner in their game. 

## The Proposal

This proposal therefore suggests a simpler alternative to what's currently implemented: a static type system. Doing this enables several things:

- Many run-time bugs become compile-time errors
- Variable types are easier to reason about while programming
- Designers can control which variables exist in their saved game files
- Compile-time analysis becomes significantly simpler
  
The end result is expected to be a simpler and more understandable experience for the user.

This proposal does mean that changes to existing code will be required. To that end, I propose an automated syntax upgrade tool for Yarn Spinner 1.0 to 2.0; its behaviour is described below.

  
## Language Changes

Variable Declaration

- **1.0:** Variables do not need to be declared before they are used.
- **2.0:** Variables must be declared before they can be used.
  - Variable declaration may be done in one of two ways:
    - The `var` instruction declares a variable, its initial value, and the type (inferred from the initial value).
      - For example: `<<var $foo = true>>`
    - The Compiler class provides a mechanism that registers a variable's declaration prior to compilation.
  - A variable can only be declared once.
  - Attempting to read or assign a value to an undeclared variable is a runtime error.

Initial Values

- **1.0:** Until they are assigned a value with the `set` instruction, variables have the value `null`.
- **2.0:** Variables always have a non-`null` value, which is set when the variable was declared.

Type Changing  

- **1.0:** A variable may be assigned a new value of any type at any time.
- **2.0:** Assigning a value to a declared variable throws an error if the type is different to its current type.
  
The `null` Value

- **1.0:** Variables can be assigned the value `null`. 
- **2.0:** - `null` is no longer a valid value. Variables never contain a `null` value.
  - `null` is still a reserved keyword, but only for the purposes of letting the compiler detect comparisons to null and forbidding them.

Operations Between Different Types

- **1.0:** Operations (for example, `<` or `+`) may be performed on values of different types; the specific results depend upon the types of each of the operands
- **2.0:** Operations between two different types are a compile-time error. 
  - If operations between different types are needed, the standard library provides functions for type conversion.

## Upgrade Path

The following steps are performed by the 1.0 -> 2.0 Upgrader.

- Variable usage and types are determined.
  - Find all variables that are accessed across all nodes, and attempt to infer their type based on sets and gets.
    - If a single type can be inferred from usage, the upgrader notes its name and type.
    - If multiple types can be inferred from usage, the upgrade process selects one, wraps all other  instances of the variable's other detected types in function calls that convert to the selected type, and emits a warning that this was done.
    - If no type cannot be inferred from usage, boolean is selected, and the upgrade process emits a warning that this was done.
- The variables are registered.
  - When the Upgrader is run from Yarn Spinner for Unity:
    - An asset that stores variable name, type, and initial data is stored.
    - This asset populated with the variable declaration data that the first step determined.
    - The importer for .yarn files is configured to use this asset when compiling Yarn source code.
  - When the Upgrader is run from the Yarn Spinner Console:
    - A new node is created in the current file (or a new file is created if multiple files are being processed at once).
    - This node is populated with `<<var>>` instructions for each of the variable declarations that the first step determined.

**Comment by unknowndevice** [comment]
Agree with this direction! It's something that's frustrated me for a while.

> Attempting to read or assign a value to an undeclared variable is a runtime error.
For a platform like Unity (and probably Unreal?) where the editor can evaluate yarn files on import, it would be more useful (for me at least) to present this feedback on import, even if it's only a warning in the console (that can be disabled in the global yarn setting?).

> An asset that stores variable name, type, and initial data is stored.
I like this idea even beyond even upgrading because it helps get track of all the variables in use. maybe something to think about in the future.

--- 

Another Unity specific thing, I'm sure it applies other platforms, but it would be nice to see all the declared variables for a yarn file in the inspector (maybe with line number), the same way you can view the amount of nodes and their names. This would help catch a lot of variable typo errors before seeing it at runtime.

**Comment by McJones** [comment]
I like this a lot, I've always been a pretty big fan of moving to a more statically typed system but I do have some thoughts around the proposal as it currently stands.

## Variable Declaration Keyword

The `<<var $foo = true>>` syntax is fine, but why is `var` the chosen keyword?
Nothing about it screams declaration to me (outside of it being the implicit type declaration keyword in C# and a few other systems).
I propose that we use `declare` as the keyword instead.
It is clearer as to its purpose in my mind than `var` which only makes sense once you know what `var` is used for in other programming languages.
This way you `declare` a variable to declare it and then `set` a variable to give it values.
While this is more typing I don't think that variable declaration happens so often that this will become onerous.
And if it turns out that `declare` is such an imposition to write, `dec` can be an alias for the same thing.

That said for the rest of this comment I will stick with the `var` keyword to keep it consistent with the proposal as listed.

## Implicit typing concerns

As it is described the idea will be to use implicit typing to work out variable types, big fan of this, but I think we also need explicit typing as well.
I am assuming part of the intent of this is to allow for more types to be added in (ints as counters come to mind) and that means we run into the problem of floats and ints looking pretty similar to each other.

so is `<<var $foo = 0>>` an int or a float?
Without some extra info we will be making a guess as to them wanting an int.
This is also related to when a variable doesn't have a sensible default even if there is no intention to ever add potential ambiguously inferable types.

### Empty declarations

As shown here to declare a variable it is given a value, what if there is no sensible default to use?
Player names is the most obvious example I can think of.
`<<var $playerName = "John">>` forces an effectively arbitrary default onto the player.
While you can do something like `<<var $playerName = "PLACEHOLDER">>` safe in the knowledge that it's going to be replaced next line this is still setting up memory that is going to just be trashed in a second.

I propose we add in explicit typing support.
This will be an optional element to the variable declaration and can be combined with or without setting a default.

```
<<var $foo = 0 as Float>>
<<var $bar as Float>>
```

I personally wouldn't allow the following however `<<var $foo as Float = 0>>` because it just reads weirdly to me, unsure if people agree though.
This will require the addition of a new keyword `as` that can only exist inside of declaration statements and new keywords for the various type names, currently `Float`, `String`, and `Bool`.
Unsure if these are the best names because I've never really liked any of them as descriptions but I guess they'll do for now.
I also think this will work better if we replace `var` with `declare`, eg `<<declare $foo as Float>>` reads pretty unambiguously to me.
This system also allows for declaring variables as constants, can just add the keyword `constant` to the type declaration: `<<var $foo = 0 as constant Float>>`.
Now there is a question as to what keyword there should be for constants, `const`, `final`, `constant` are all likely candidate, personally `immutable`, `enduring`, or `eternal` are my favourite slightly out of the box options...

Empty declarations does however raise the potential of encountering null in a variable.

## Null handling

As currently described nulls are now banned, total agreement with this, but I don't know if this is something we can promise.
As C# currently doesn't exactly have the best system for optionals we essentially have to assume that the variable storage system will encounter a null value and deal with it.
This is also a possibility if we allow non-default variable declarations like I described above.

Most of these can be caught at compile time and throw errors before running the program so I don't think it is a huge problem but it does still need to be handled.
In that case I propose that encountering null is an error and crashes or throws an error, not sure which is better.

Overall though I am totally down with the proposal and think it makes perfect sense.

**Comment by unknowndevice** [comment]
for the float vs int I would just have it so `var $foo = 0` is int var `$foo = 0.0 `is float. without the decimal on declaration it's always an int. I think that's simpler. either solution is fine! my preference is less typing.

**Comment by McJones** [comment]
I'm just thinking about how Swift and Rust (as my goto examples of static languages with implicit typing) both encounter and deal with this issue (and many of their examples use float and int) by having an explicit typing option.
They still suggest implicit is the way to go most of the time but realise this isn't always possible.

The reason I don't like relying purely on inference is mostly because to me with my old programmer brain I can easily see the difference between `0` and `0.0` but to someone without that background it makes little sense to go *"oh so here's the thing you need to add a .0 to the end or else it won't know"*.

It hides the explicit desire of wanting a decimal value behind an implicit understanding of how the inference system works and the difference between floating point and integer numbers.
And frankly that there is a difference in a computer between `0` and `0.0` is so annoying.

Of course this is all moot if numeric values are always going to be floats.

**Comment by WeslomPo** [comment]
I think we should choice double over float, because on practice float tends to be very problematic even on small numbers. It have only 6-9 significant digits where double have 15, and on paper it feels good, on practice it is a pain to deal with. 4bytes over per variable is not significant (because any pointer or boolean is 8bytes on 64bit). 
And also, here no need integer values either - with double precision we have plenty of room to work with them as double. I think not so many people will calculate scientifically precise functions on YS :) - so there no difference between 0 and 0.0.

I suggest add enum and set operations with them - it will help to make inventory, or another some kind of wonderful things. A mean union, difference, include, exclude - etc.  Enum not like in C#, but more like a set of predefined values that can contain any or no one of them. Like: `<<enum Items { Spoon, Fork, Glass }>>`, and variable `<<set $Inventory:Items = {}>>`, then we add something into `<<$Inventory add Spoon>>`, and we can check `<<$Inventory contains Spoon>>`, or `<<$Inventory contains $purchaseList>>

**Comment by unknowndevice** [comment]
I'm not sure what place enums have in yarn scripts, but I will say I do a lot of enum converting in my C# from yarn commands. I just rather it over string comparison.

an example case might be <<move characterName left>> where there's a position enum { OffStageLeft, Left, Center, Right, OffStageRight }, and each enum has a value to match.

**Comment by McJones** [comment]
Sorry I should have been a bit clearer, I didn't mean to say YS should be specifically using floats in preference to doubles, I was talking more about floating point numbers in general and just using the term float to encapsulate them.
If I had complete control I would use [Decimal type](https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=netcore-3.1) in the C# implementations for decimal numbers as it more accurately represents what I **think** people want to do with decimal numbers in YS.
From my experience though people are mostly using numbers as basic counters, "*how many times have I spoken to this character?*" or "*do I have enough gold to bribe the guard?*" sorta things which is why I said ints make sense as a type to exist in YS.
it is more a historical artefact than a design decision that numbers in YS are floats, I would hazard a guess that if we were to replace the floats with ints we'd break nothing but a couple of custom commands and a few `wait`'s here and there.
Not that I am saying we should do that, just that I don't actually see decimals being used much.

With all of that said as to not having ints, determining correct type for decimal numbers, and to adding enums and sets (which is an idea I do like) I think that is out of the scope of this proposal so we should try and stick to the issue at hand.
I think regardless of the types we covet in YS it looks like there is rough agreement that we need a stronger type system to support them.

**Comment by desplesda** [comment]
Yeah, this thread is less "what types should Yarn Spinner support" and more "how should Yarn Spinner deal with types in general."

So far, the responses from folks here are sounding like static typing is the way to go. Unless I hear a valid objection (which I'm not ruling out!), I'll begin the design work on this at some point next week.

**Comment by desplesda** [comment]
To @McJones's comments earlier:

* Happy with `declare` as the keyword over `var`.
* If we allow variable declaration that declares a type without specifying a default value, we run into a problem where a node is run that gets the value of that variable. Yarn Spinner can't predict which nodes are called in which order. Most languages that I know of solve this problem by defining a default value for types (e.g. zero for integers, the empty string for strings - details vary by specific language). That could maybe work?
* Happy to allow explicitly specifying type.

@WeslomPo Yeah, values that are constrained to an enumerated set of values would be good, but I think that that's worth a separate proposal.

**Comment by Schroedingers-Cat** [comment]
> Variables must be declared before they can be used. 

I wonder if that makes it more difficult for writers to use. If they have to make sure that a variable has been declared before they can use it in their scripts, they'll have to deal with something that worked automatically for them during v1. What if they want to use a variable in some dialogues that could be encountered in any order by the player? It sounds like with v2 they have to be sure which of their yarn scripts starts first.

Generally, I like the proposal a lot. I'm also in favor of using `declare` instead of `var`.

> An asset that stores variable name, type, and initial data is stored.
From the proposal it sounds like this only happens during upgrading. Will this also be the default behavior for new variables created with YS2?

**Comment by desplesda** [comment]
> What if they want to use a variable in some dialogues that could be encountered in any order by the player?

Variable declaration is a compile-time thing, not a run-time thing. It might help to think about how C# does class declarations - it doesn't matter in which file a class is defined, just that it's declared somewhere. Similarly, a variable would only be allowed to be referenced if the compiler has a declaration for it somewhere.

And yeah, this proposal does reduce flexibility somewhat by requiring that a variable be declared, rather than just allowing effective implicit declarations. However, it reduces runtime errors, makes it easier to integrate into more complex systems, and helps new authors joining a project understand its structure ('what does this variable do? what can be stored in it?')

> Will this also be the default behavior for new variables created with YS2?

We can auto-create the asset during upgrade, and in Unity we can offer a button on the Dialogue Runner that creates a new empty variable registry asset in a similar way to how the Post-Processing Layer lets you click a button and generate a Post-Processing Profile asset to start working with.

**Comment by Schroedingers-Cat** [comment]
That's sounds all great!

**Comment by McJones** [comment]
Had a thought around this just now, with the `<<declare var = value>>` and how this could tie into project metadata in a variable registry.
What if we have an optional way of declaring variables, so the above which does a straight up declaration and one that supports an arbitrary comment, eg `<<declare var = value, "a string where I can describe anything I want">>` which Is then passed along to the variable registry.

This comment can then be shown in Unity or in the editor giving hints as to the intent behind the variable.

**Comment by desplesda** [comment]
I like this a lot. Happy to include this in the final feature.

**Comment by unknowndevice** [comment]
This is something I've mentioned in the slack before, so I would very much like this!

**Comment by desplesda** [comment]
This feature is now largely implemented, and is being worked on in [`feature/static-typing`](https://github.com/YarnSpinnerTool/YarnSpinner/tree/feature/static-typing). 

Implemented:
- [x] Variable type declarations, both in the source code and provided directly to the compiler
- [x] Expression type checking
- [x] Function type checking (both the parameters and the return type)
- [x] Removed the value `null` (the keyword is still reserved, but it's now no longer allowed to be used in an expression)

Still to come:
- [ ] Variable declarations with just types (`<<declare $x as number>>`, etc)
- [ ] Making use of default value (currently the value is ignored, just their type is used)
- [ ] Type conversion functions (`str()` etc)
- [ ] Variable description annotations
- [ ] v1.0 to v2.0 language upgrader

**Comment by desplesda** [comment]
(As part of doing this, the information you need to supply to the `Compiler`has changed, since you need to specify a `Library` in order for function type information to be available. As a result, YarnSpinner for Unity and Yarn Spinner Console will need to be updated.)

**Comment by desplesda** [comment]
With the language upgrader added in 77dde520470004a8071aa2f57cc5c28c5c50e06b, this feature is now added, and I'm closing this issue! Thanks to everyone for their help!
