### ISSUE TITLE
Trouble porting test suite to JSON

### ISSUE THREAD

**Issue by fadookie** [YarnSpinnerTool/YarnSpinner#261]
Hello Everyone,
Recently I have been working with my friend Jonathan, the author of [YarnGDX](https://github.com/kyperbelt/YarnGdx), to create a headless, vanilla Java version of his library that will be useful for all JVM applications, not just libGDX ones.

As part of this effort, to help ensure that our work is accurate, I have been porting the YarnSpinner test suite to Java.

One thing he mentioned was that he only uses the JSON format personally, and we've noticed during this process that our `.yarn` format support is buggy.

It would be really helpful to get a copy of all the `.yarn` files in the [Tests](https://github.com/YarnSpinnerTool/YarnSpinner/tree/master/Tests) folder in `.json` format so we can compare our support for both formats.

However, when I tried to use Yarn Editor to convert the files, I noticed that most of them will not load in the editor. It just shows an empty screen.

If somebody could help us get some `.json` versions of these files it would be very helpful. Also it might be nice in this repo for the tests to run against both formats as well to ensure compatibility.

**Comment by McJones** [comment]
Hey-oh,

So about a year ago now issue #173 was opened asking the question if the core library of Yarn Spinner should remove support for JSON.
The general consensus there was to remove support for JSON from the library but to leave it in the editor.
We removed it because it added extra complexity to handle and even then we still had to parse the yarn inside of the JSON anyways.
There are more details in the issue linked above if you are curious.

The editor support was kept around however for this very reason, people wanting to still use JSON as the transmission format.
I am not sure why the editor is having issue, but it feels like it is related to the editor and not the library, so it might be best [asked there.](https://github.com/YarnSpinnerTool/YarnEditor)

I'll leave this issue open for now in case I have misunderstood your issue, please let us know if that's the case.

**Comment by fadookie** [comment]
Thanks, I understand. Although it would still be nice if the `.yarn` files in the `Tests` folder could be opened in the editor at least.
