### ISSUE TITLE
Pound Signs (#) in dialogue fail to compile

### ISSUE THREAD

**Issue by axikita** [YarnSpinnerTool/YarnSpinner#267]
**What is the current behavior?**
A pound sign (#) anywhere in the dialogue returns an error and the dialogue does not run.

This also breaks any unity Rich Text color tags using hexadecimal colors. A line like
`this text is <color=red>colorful</color>`
works fine, but a line like
`this text is <color=#ff0000ff>colorful</color>`
will produce the error.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

This edit of Sally.yarn from the demo scene will trigger it:

```
title: Sally
tags: 
colorID: 0
position: 524,111
---
Player: Hey, Sally. A pound sign: # How's it going? #line:794945
Sally: Oh! Hi. #line:2dc39b 
===
```

**What is the expected behavior?**
The compiler treats the pound sign as plain text if it is not tagging some expected feature. 
Unity rich text tags with hexadecimal are usable.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.0
  - Unity Version: 2019.4.1f1 Personal

**Other information** 

The error returned is:
```Error on line 6 at position 43:
extraneous input 'i' expecting {HASHTAG, BODY_HASHTAG, TEXT_NEWLINE, TEXT_HASHTAG, TEXT_COMMANDHASHTAG_HASHTAG, TEXT_COMMANDHASHTAG_NEWLINE, HASHTAG_TAG}
Player: Hey, Sally. A pound sign: # How's it going? #line:794945
```

This links to YarnImporter.cs line 154.
I suspect the issue is happening somewhere within the yarn compiler, which I'm unable to edit.

I looked through the yarnspinner documentation, and the only use of a `#` I could find was the localization tags.
I wonder if this could be fixed by ignoring any `#` that is not followed by `line:` or another recognized keyword.

I uploaded an edited YarnImporter.cs as a .txt that worked as a temporary fix for me.
[YarnImporter.txt](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/files/5011518/YarnImporter.txt)

Regex is used to replace all "#"s not used by the localization system with "_OCTOTHORPE" before the text is compiled
After compilation, the stringTable is recreated, and instances of _OCTOTHORPE are converted back to # signs.
While this fixes the # issue, I haven't checked to make sure it doesn't break anything else, namely, localization.

**Comment by desplesda** [comment]
This is an issue in the compiler, so I've moved it to that project!

**Comment by StefanJanssen95** [comment]
I've seen multiple issues (#274,  surrounding some characters being specifically used in the YarnSpinner syntax. I suggest creating a way to escape those characters to still be able to use them. As far as I see the backslash (`\`) is not used yet in the syntax.

My suggestion:
Whenever a YarnSpinner specific syntax is found make sure there is no backslash before it, if there is ignore it. 
To avoid breaking older scripts a backslash in front of a character not part of the syntax should remain where it is. 

I would be willing to implement this if this is approved (or with some remarks)

**Comment by kyl3r92** [comment]
Just started with Yarn, using it in Unity. After I got it working, I added a colored word. (Web Editor even offers it: https://yarnspinnertool.github.io/YarnEditor/). Unity threw an error upon importing. It said "extraneous input '<' expecting {HASHTAG..."

So apparently the html color tag <color=#f2f2f2>text</color>  will not work out of the box. I mean - even Unity Debug Console can display colored text...

I fixed it like this:
In YarnImporter.cs  Line 66: (encode it)
var sourceText = File.ReadAllText(ctx.assetPath);
sourceText = sourceText.Replace("<color=#", "COLOR_TAG_BEGIN"); // ADD THIS
sourceText = sourceText.Replace("</color>", "COLOR_TAG_END"); // ADD THIS
string fileName = System.IO.Path.GetFileNameWithoutExtension(ctx.assetPath);

Das Gegenstück in DialogueUI.cs Line 281: (decode it)
// The final text we'll be showing for this line.
string text = localisationProvider.GetLocalisedTextForLine(line);
text = text.Replace("COLOR_TAG_BEGIN", "<color=#");  // ADD THIS
text = text.Replace("COLOR_TAG_END", "</color>");  // ADD THIS


I tried to use premade HTML Encoding functions, but none worked out of the box. If you encode the "<<stop>> commands as well, you'll have a problem. 
So I encode the text but decode it before pushing it into TextMeshPro. Note, that you cannot do this on-the-fly in "OnLineUpdate(String)" because the half-finished string will not be decoded correctly. Imagine "hey <color=#f2f2f2>user</color>" being "hey <col" during animation... I avoided this problem with the above fix. 

Anyway, I would have expected YarnSpinner to have this functionality covered...

**Comment by StefanJanssen95** [comment]
@desplesda Can you take a look at this issue and see what the best way to handle this in the future is? That way people could implement the fix.

I've made a suggestion, but there might be a better way?

**Comment by desplesda** [comment]
This is likely something that we can attempt to fix by being smarter about it in the parser, where we detect that the `#` is being used inside of some kind of markup. I'll see what can be done in this area. In the meantime, a workaround is to replace the `#` symbol in your code with a different symbol (like `%`), and replacing that symbol in the line at runtime.

**Comment by kyl3r92** [comment]
@StefanJanssen95 @desplesda 
I have to mention: My suggestion does not fix the text in Options yet. And the "<col..." ist still visible during animation, I'd need to add extra logic for that. 
So I would highly appreciate a solution that does proper escaping.

**Comment by StefanJanssen95** [comment]
> @StefanJanssen95 @desplesda
> I have to mention: My suggestion does not fix the text in Options yet. And the "<col..." ist still visible during animation, I'd need to add extra logic for that.
> So I would highly appreciate a solution that does proper escaping.

I agree that this issue is bigger than just the `#` and I don't think "doing smart detection" is the best solution. It's impossible to know if I actually want to print <col=#BADA55> in my text or not.

**Comment by VivienLynn** [comment]
Someone recommended me to use TMP Styles Sheets as a workaround. You can learn about this here
([https://learn.unity.com/tutorial/textmesh-pro-style-sheets-and-styles](url)).

While this did not seem like the best solution, I must say that I realized that it is quite useful.
For example, if you have a specific color for Locations or Items, you can always use something like `<style="ItemName>Zerstörer</style>`. If you later in development decide to change that color, font or if it should be bold, italic, all upper case or whatever you want it to be, you can just go to the Style Sheet, change it there, and it will be fixed for all your dialogue lines.

**Comment by houkanshan** [comment]
I got a related bug: **Can't put URL in text.** 

If I send:
```yarn
Sally: Hey check out this http://github.com/YarnSpinnerTool
```

What I get:
```yarn
Sally: Hey check out this http:
```

Because yarn will parse `//github.co...` in as a comment. 

A temporary walkaround is adding a useless markup in between `//`. (Require YarnSpinner 2.0+)

```yarn
Sally: Hey check out this http:/[x/]/github.com/YarnSpinnerTool
```

Really wish their is an escape character!

**Comment by radiatoryang** [comment]
There are already plans for an escape character in the Yarn language 2.0 spec https://github.com/YarnSpinnerTool/YarnSpinner/blob/yarn-spec/Documentation/Yarn-Spec.md#escaping-text

but no ETA on when that'll get implemented, maybe by the end of this year?

**Comment by desplesda** [comment]
Or even sooner! f1dc0ee2d9f303adef729ea1a733ff708551d6c1
