### ISSUE TITLE
visited is not a valid function

### ISSUE THREAD

**Issue by SirYakalot** [YarnSpinnerTool/YarnSpinner#292]
Hi there, I'm trying to understand how yarnspinner works but I'm hitting an error and I'm not able to really understand what it's trying to tell me. I know the syntax of the yarn file is correct, but I have two dialogue runners with seemingly identical set ups and one works while the other doesn't. What exactly does this error mean? 

Thank you!

![image](https://user-images.githubusercontent.com/4086317/106388515-dc828c80-63ac-11eb-901a-71041b334dd9.png)

**Comment by radiatoryang** [comment]
The `visited()` function is not built-in to Yarn. The Space example implements it with an additional script next to the Dialogue Runner called `NodeVisitedTracker.cs` :

https://github.com/YarnSpinnerTool/YarnSpinner-Unity/blob/main/Samples~/Space/Scripts/NodeVisitedTracker.cs#L22

... so the most likely fix is that you need to add that script to your Dialogue Runner:

In the future, please file Unity-specific issues on the YarnSpinner-Unity repo (https://github.com/YarnSpinnerTool/YarnSpinner-Unity/) instead of this main YarnSpinner repo

And if you need help, you can get a faster and better response by asking in #help on the Discord https://discord.gg/9CvsQfS

**Comment by SirYakalot** [comment]
Thank you! that file is actually already attached BUT I'll ask in those other places. thank you!
