### ISSUE TITLE
Proposal: Porting the Runtime to C++

### ISSUE THREAD

**Issue by JoshLee0915** [YarnSpinnerTool/YarnSpinner#299]
# Introduction
Before I begin I want to say I am very impressed with YarnSpinner. I needed a a dialog system for a game I am making with a group of friends and I remembered hearing about this tool in a GDC talk by Secret Lab, and since a fair number of people I work with know twine I figured it would be worth checking out porting it to Godot. The further I dug into the tool the more impressed I became with the tools simplicity and flexibility.  

While it was easy enough to port the runtime to Godot using the Mono version of the engine, the fact that the plugin requires the Mono version of the engine hampers general adoption by the community since the standard version is more preferred for its stability and lighter weight unless performance is a concern. If the runtime was instead in C or C++ I could have instead used Godot's GDNative system to write a plugin that would work across both versions. Along with this I know a hand full of Unreal devs that are looking for a dialogue engine for their games, but can not use YarnSpinner due to being implemented in C#.

# Rationale
By at least rewriting the runtime in C++ it would allow YarnSpinner to be ported to and used in a much wider array of engines then it currently is due to the fact most engines support binding native binaries in some manner and that C++ can be compiled into web assembly.

Also, since YarnPrograms are just protobuf schemas, they already provide a nice language agnostic interface that can be used to separate the compiler and runtime to help reduce what needs to be rewritten/ported.

# Proposed Solution
This is a very rough solution but I think in general would be a good way to approach rewriting YarnSpinner in C++.

1. Rework the YarnSpinner runtime and compiler to use Protobuf to define common data schemas and provide a decupled language agnostic interface
2. Split the Compiler from the YarnSpinner Runtimes and possibly merge it with the YarnSpinner-Console to create an independent compiling tool/library much like what is seen with projects like Protobuf. This will also allow the compiler to stay in C# while the runtime is in C++
3. Port the YarnSpinner runtimes to C++
4. Possibly port the Compiler to C++ latter and/or maybe directly integrate into the editor

# Backwards Compatibility
While this would be a massive change it should remain backwards compatible, though the unity integrations will need to be reworked.

# Notes
As discussed in issue #24 I plan on trying to do this once I get time as I would love to be able to make this tool a GDNative plugin, but my main concern would be continued maintenance of it and keeping it up to date with new features so I figured it would be intresting to start a conversation around it beforhand.

**Comment by xsduan** [comment]
I have had thoughts on building a Rust version as well (just due to personal curiosity of wanting to justify learning Rust, not really out of need) if you're willing to futz around with rust-to-cpp bindings. If you'd be interested in that in particular then I can bump that up a few priority levels up.

**Comment by McJones** [comment]
Hey-oh, thanks for the proposal, you've clearly put a lot of thought into it.

One of the main reasons why we defined the compiled yarn programs as protobuf (with a CSV strings table) was for the purpose of making porting the runtime over to other languages and environments easier.
And before COVID obliterated all useful scheduling I had started work on a [C++ runtime and front-end for UE4](https://www.lonely.coffee/blog/2020/4/20/ue4-protobuf-and-yarn-spinner) and have made a few toy runners in other languages for my own side-projects.
With that said there are things in the project that are assumptions made for C# (and even more specifically for Unity) but none of these are huge deal breakers and couldn't be worked around or redesigned.
So colour me as interested in the core idea of making more parts of Yarn Spinner cross-platform.

With that said I do have some thoughts about this and I realise you are talking about the runtime but I want to try and go through my thoughts around making a platform-neutral YS in total so that I hope my views about this proposal make more sense.
There are essentially three parts to Yarn Spinner: the compiler, the VM/runtime, and front-end each with their own quirks and advantages and disadvantages to being made cross-platform.

## Front-end

No matter what the situation I believe the front-end (so for example [Yarn Spinner Unity](https://github.com/YarnSpinnerTool/YarnSpinner-Unity) in the case of Unity) will have to be written locally for that tool.
In this case front-end means both the UI side of Yarn Spinner but also other elements like integration with the tooling, YS has a whole bunch of custom Unity editors for example.
There are just so many platform specific quirks that each tool has that you'd end up losing enormous amount of time writing wrappers to handle them all.
I fear even attempting to make a cross-platform front-end that is either doomed to fail or create a substandard result.

## Runtime

The VM and runtime (and many of its associated components like the variable storage and library) are relatively small and straightforward to port (or perhaps even do with codegen) to the target environment.
However the "correct" way of performing functions will vary on an environment by environment basis, as an example of this yarn functions in C# are delegates, but in Swift you'd do them with a closure, and in C++ I would start by making functions with std::function.
Each of these have different assumptions as to how they are called and how they are stored.
These small differences have an enormous number of complications.

This is the core area which would need to be changed, you mentioned "common data schemas" the biggest of which would need to be a wire protocol for functions.
I think [grpc](https://grpc.io/about/) offers the most guidance here as to what it would need to be.
However I don't think we want to be defining new protobuf for each function, so we'd have to make ours a bit more generic.
An inital pass (very WIP) at something like this would be:

```protobuf
message Function
{
    enum ReturnType
    {
        NUMBER = 1;
        BOOL = 2;
        STRING = 3;
    }

    string name = 1;
    int32 parameterCount = 2;
    repeated Operand parameters = 3;

    ReturnType return = 4;
}
```

Now grpc breaks their inputs and return into their own messages and I am not entirely sure why, would have to do some more research to see if that is worthwhile.
There is still a lot to be solved here, especially around how functions work and if they should be blocking or not.
And how the runtime would handle incorrect returns or parameter mismatches is also a big hmm.

There are also going to be some things around types to be figured out, in particular strings.
Now for unity we can get away with protobuf strings and C# strings being similar enough but in UE4 fstrings are weird and they'll need to be massaged into shape.
I imagine there will be other issues in other languages and tools we haven't thought of yet.
Regardless something like this would be the start.

With that said I think starting by going "lets make a proper cross-platform runtime" is too big a starting point.
I think moving the existing runtime over to C++ and doing it in a C++ specific way is gonna be easier first and then we can work on making cross-platform protocols that can be adopted.

## Compiler

Finally the compiler, which I think is the best candidate for porting away from C#.
While compiler is written in C# it uses ANTLR to do the parsing side of things before we take over, meaning a huge chunk of any porting work is already done assuming there is an ANTLR target for language (of which there are many).
The final output of the compiler is the Yarn Program (protobuf) and a strings table (CSV), again huge support for these.
Addtionally the input is the collection of files to be compiled (and a few option flags).
The compiler currently however doesn't have a defined output for errors or warnings, but that is very resolveable.
This in my mind is the perfect starting point for cross-platform porting of Yarn Spinner, it has clearly defined input, a clearly defined purpose that all other components need, and already has a (mostly) cross-platform output.

## Conclusions and random thoughts

In summary I am all for the idea of making Yarn Spinner more cross-platform but there is an enormous amount of work here.
Of the three pieces of Yarn Spinner the compiler makes the most sense to be made cross-platform and the front-end can never really be made cross-platform in any meaningful way.

The runtime can be made cross-platform but that has a lot of problems to be solved and regardless of anything else if you want to make a C++ runtime (regardless of it being cross-platform) *please please please* go for it, we will help where we can (assuming it uses a compatible OSS license).
But starting with the goal of making it cross-platform in my mind feels very big.
Not trying to discourage you but having a C# and C++ runtime and front-end for that runtime (for say Godot or UE4) and then moving towards a cross-platform version just makes more sense to me than trying to making it cross-platform from the start.

Finally I second the comment by Shaun about doing it in Rust over C++.
Rust has a great many of the advantages of C++ (including webasm support) and far far far more protections than C++, it makes a lot of sense to me that if we are going to make a library form of Yarn Spinner to do it in Rust than C++.

Again, great proposal, have any thoughts on what I've said?

**Comment by xsduan** [comment]
Right, so I spent the last 2 evenings making a small prototype (still yet to be finished), and a lot of that was just looking through the design of the current program.

> The VM and runtime (and many of its associated components like the variable storage and library) are relatively small and straightforward to port (or perhaps even do with codegen) to the target environment.
However the "correct" way of performing functions will vary on an environment by environment basis, as an example of this yarn functions in C# are delegates, but in Swift you'd do them with a closure, and in C++ I would start by making functions with std::function.
Each of these have different assumptions as to how they are called and how they are stored.
These small differences have an enormous number of complications.

One thing I have with this is that there just isn't a spec for the VM at all -- the entire spec for the current file is about the syntax of the yarn files, which I guess, fair enough, it isn't something that was planned on.

Here are some things I've noted, totally unprofessional (I've never worked with compilers) so I may be off the mark on some:

- The VM relies on strings a lot. For example, the line numbers could be an u32 but it is loaded as a string. This makes implementing in native languages difficult for the reasons you said.
- For the same reason, static jump commands should be compiled to take an offset rather than a string, and variables should be referred to by static memory offset where possible.
- Similarly it would be nice if the function call strings were known in advance in a table somewhere so we could fail early for a program in a given context, or to optimize lookups in languages where function pointer overhead was far less than the dict hash overhead or if it's just plain annoying to use strings everywhere
- `CallFunc[op_s] <argc> <values>...` feels wasteful when there's no way to have truly variadic parameters to my knowledge (it's always known at compile time). Something like `CallFuncStatic[op_s][op_i] <values>...` feels like a more natural fit for Yarn's capabilities.
- I don't see anything in the VM format that would allow us to take advantage of this:
   > Variables in Yarn should be declared to let the implementing program know the type of values they hold. The intent of this is to allow the implementing program to set up memory and to provide guidance as to the usage of a variable directly from the writer. The declare command has four components: the keyword, the variable, the operator and the value, and must be presented in that order.

  Aside from the strings this means that we have a bounded memory size, so that makes memory management of bools and numbers basically trivial.
- It would be easier/more natural to load into memory if all the instructions were contiguous and the nodes simply pointed into the entry point -- as far as I can tell every node is appended with a `Stop` instruction anyways.
- It might be easier/more natural in a game dev context to just use an embedded Lua instance (straight to Lua bytecode if possible). As a nice bonus we could implement and extend corelib in Lua instead of having to hook it up with each arch/language/game engine (?) we want to port it to. I do realize it's a bit of a cop-out though.

None of these are insurmountable for a new implementation but I think if we're gonna end up speccing out the VM we might as well make some QOL improvements while we're at it.

I've tried to keep my comments as realistic as possible as I know this isn't, like, HotSpot or anything, so it's usually gonna be pretty light on the actual calculations. Most of these are meant as ideas for ease of implementation across low-level languages more than potential performance gains, though I haven't had much experience there so I might be off on some.

**Comment by JoshLee0915** [comment]
Wow, thank you @McJones for such a detailed response! You make some very good points and I have actually hit some of those issues with the godot port I did as GDScript does not treat functions as first class citizens. 

Its unfortunately too late for me to read through it in detail but I wanted to answer your question on why grpc breaks their inputs and outputs into different messages. You actually do not have to do it but it is highly suggested to do so in their standard to allow for independent schema evolution of the inputs and outputs. That is the only reason they do it that way.

@xsduan, that is really cool! I have been meaning to dig into Rust when I get a chance but have not had a good reason to yet. I did consider it myself as Godot has a 3rd party Rust binding, but I personally think C++ is probably the better choice mainly for portability. I can not get into details now but I hope to respond to you in better detail this weekend after I get a chance to read your full response. 

I do have to say I do agree with @McJones's assessment that it will be more memory safe but to my understanding Rusts largest advantage in safety with concurrency and parallelism as you can get similar memory and type safety from using a RAII paradigm in C++ and I am not sure how helpful that may be with how the runtime is currently setup but I could be wrong as I have not looked very far into Rust yet and this is just a random thought on it.

**Comment by McJones** [comment]
Hey-oh, me again, thanks @JoshLee0915 and @xsduan for the comments, I hope I can shed some light on some of this stuff.

> One thing I have with this is that there just isn't a spec for the VM at all -- the entire spec for the current file is about the syntax of the yarn files, which I guess, fair enough, it isn't something that was planned on.

Right yeah so yeah... so the VM was initially written by Jon and used JSON as its serialised form, we moved away from that protobuf for a variety of reasons but we never actually documented it because it was always sorta intended to be hidden away. As the desire for more platforms grew we went "oh neat, well the VM is protobuf already" and never actually got around to describing how it all works.
Hopefully it was too weird.

> The VM relies on strings a lot. For example, the line numbers could be an u32 but it is loaded as a string. This makes implementing in native languages difficult for the reasons you said.

hmm I think this is one of those things that just never occurred to us due to the evolution of Yarn Spinner, in our mind the Yarn file is the source of truth and the lineIDs are strings hence why we went with strings. But there is no reason to stick with that,  switching it up to use u32 makes sense.

> For the same reason, static jump commands should be compiled to take an offset rather than a string, and variables should be referred to by static memory offset where possible.

Likewise this is sorta vestigial element of the evolution of the VM, key based lookups work absolutely fantastically in JSON, but agreed makes sense to change it.
As to the variables though I doubt that will change much if only because being able to override the variable storage system is a thing many people do and if that was baked into the VM instead of its own system it would be much harder.

> It might be easier/more natural in a game dev context to just use an embedded Lua instance (straight to Lua bytecode if possible). As a nice bonus we could implement and extend corelib in Lua instead of having to hook it up with each arch/language/game engine (?) we want to port it to. I do realize it's a bit of a cop-out though.

Honestly doesn't feel like a cop-out to me, this actually makes a lot of sense. Gonna have to think about this one a but more.

As to the rest of your comments @xsduan, especially around functions I will have to think some more about it before being able to respond, but much like with variables functions are one of those things where we tend to let the users have complete control as much as that means we end up having to be a bit goopy on our end.

Finally @JoshLee0915 yeah my comments about Rust is less that C++ can't be safe just that it is easier to be safe in Rust.

Thanks again so much for the comments, much to think about, so much to think about now.

**Comment by JoshLee0915** [comment]
Now that I have had a bit more time to review the responses I hope I can provide some better thoughts on what was stated. Now before I start too much Its been a bit since I looked over the runtime and I need to dig into it a bit more, so some of this may be me talking out of my ass and if so I apologize in advance.

> However the "correct" way of performing functions will vary on an environment by environment basis, as an example of this yarn functions in C# are delegates, but in Swift you'd do them with a closure, and in C++ I would start by making functions with std::function.

This is a good point but I think a larger issue has been missed here and that is there are some languages, like GDScript, that do not treat functions as first class citizens at all. This means that we can not guarantee the ability to even pass functions in all instances, but I do think there is an easy solution to this issue. May I ask if you all ever considered moving the runtimes to a more event based system?

YarnSpinner seems quite well suited to it as when I think about it YarnSpinner has 3 major events (not counting the on completed and started events)

1. Display Line
2. Display Options
3. Execute Command

By switching the system to an observer like pattern I think it could help to decuple the runtime from the front end and help simplify writing interops for ir as well as making it more language agnostic. 

I agree with @McJones that I think the Runtime should stay away from choosing how to handle functions and variables. To me as a tool writer that is very engine specific stuff and I think should be left up to the tool writer. In my eyes the runtime should really only care about how to load and run the VMs (and take care of some standard commands like wait and stop), translation, display, function calls, and variable storage should be left up to the engine specific implementation.

Also, while I kind of agree with @xsduan comments on changing the lineIds from strings to ints I actually think they are best left as strings. Assuming its the `sourceTextStringID` that is declared in the proto file allowing them to remain strings allows for the encoding of metadata that helps prevent collisions since you can load multiple compiled yarn files into the runtime and it will merge them together if I remember correctly. While I know it may not be the most efficient way to do it I actually think there is not harm in keeping it that way personally.

Finally, to clarify some of my thoughts on Rust my main concern with it is that it would hamper or at least not help adoption as much as doing it in C++.  In general while there are some Rust based engines out there, I think its a safe bet that C/C++ dominates the market with the largest engines having better support for it. This increased support means lower barriers to entry for tool programmers. 

For example if I was rewriting my plugin for GDNative I would much prefer to include the runtime as a git submodule then having to link a lib with a C interop. 

There is also the question of setting up interops but tbh I personally think that argument is a wash in both directions after thinking about it. There is some complications with a Rust to C interop and it would require a C interop to have to be maintained by some one but I think these issues are fairly minor.

In the end I think the question of Rust vs C/C++ is a question of easy to write stable code vs ease of adoption. Since I proposed this with easing adoption in mind that is why I personally support C++ over Rust though I do see the advantages of using Rust.

Either way I am happy to see there is interest in the matter. Once I get time I will try to get to work on a port of the runtime to C++ with maybe some of the changes I mentioned above. Thank you very much for taking the time to consider my proposal!

**Comment by alexclaydon** [comment]
Hello, I've just watched the GDC talk on YS (published 31 May 2022), which mentioned that Unreal Engine integration was in development. I've had a look at open issues here on the repo but this thread was all I could find. Would someone on the team be able to provide any updates on timing or roadmap for UE5 integration? It's such a great project, would love to work with it. Cheers.

**Comment by janhohenheim** [comment]
Regarding Rust: 
We just finished porting the entire compiler and runtime 🎉
See our crate [yarn_slinger](https://github.com/yarn-slinger/yarn-slinger).

**Comment by VirtuosoChris** [comment]
Re: A C++ Runtime :
I'm not affiliated with the official Yarn Spinner project at all, but I ported the runtime to C++ to use in my custom engine.
If anyone arrives at this thread via Google search, I hope it's useful!

[https://github.com/VirtuosoChris/YarnMachine](https://github.com/VirtuosoChris/YarnMachine)

**Comment by JanVelas** [comment]
> Re: A C++ Runtime : I'm not affiliated with the official Yarn Spinner project at all, but I ported the runtime to C++ to use in my custom engine. If anyone arrives at this thread via Google search, I hope it's useful!
> 
> https://github.com/VirtuosoChris/YarnMachine

Thank you so much.

**Comment by desplesda** [comment]
Thanks, all! In addition to these excellent third-party C++ and Rust implementations, a C++ version of the runtime is also part of [Yarn Spinner for Unreal](https://github.com/YarnSpinnerTool/YarnSpinner-Unreal/tree/17ede9aeb3dfaf4845b9fa344e4642fd0461ab43/Source/YarnSpinner/Private/YarnSpinnerCore). I'll close this issue here. Thanks again for the discussion!
