### ISSUE TITLE
<<jump>> command should accept string variables

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#301]
**Is your feature request related to a problem? Please describe.**

The `<<jump>>` command jumps the execution to a node. Currently, the `<<jump>>` command takes a literal, which means that jumps are always hard-coded. However, the actual lookup is done at runtime, and the compiler performs no compile-time checking to ensure that the node name provided actually exists.

**Describe the solution you'd like**

To allow further flexibility, the `<<jump>>` instruction could be modified to allow the use of a variable name. This would allow users to create more dynamic flow through their scripts.

We'd want to do type checking on the variables that are being used - for example, only string variables would be appropriate to use in these commands.

**Describe alternatives you've considered**

Alternatively, we could go the other way, and add logic to the compiler to make it certain that the user is directing the compiler to jump to a known node.

It's worth noting that if the target of a `<<jump>>` is dynamic, it's a lot harder to determine a Yarn program's control flow graph.

**Comment by dogboydog** [comment]
Just my opinion but I think it should work with a variable node name. There are valid use cases for this. The main one that came up is randomly picking a node name from a list. But I could also imagine other use cases. Thanks

**Comment by McJones** [comment]
There's been a bit of discussion around this on the discord so I thought I'd chuck in my two cents.
While I think this is a good idea I do think it should still follow all normal command rules for inserting values into commands.
That is to say that you can go `<<jump nodename>>` just fine but if you want to use a variable you'd go: `<<jump {$nodename}>>` or `<<jump {"nodename"}>>` if you are using direct values (not sure why you'd do this but functionally it would be the same).
Of course the regular `<<jump nodename>>` would still work just fine and would be the recommended manner of moving about.

I have a few reasons for this, first it keeps the rules for commands as common as possible and limits the number of special case commands.
Considering how long we have had the language not being able to dynamically define jump points for nodes and the relatively small number of people asking for it I think its fine if it doesn't get special treatment like `if` or `set`
The only reason we have any commands that don't require interpolation (like `if`) is because they are so common place that requiring the interpolation each and every time would be onerous.
Secondly, it makes it clear that you are doing something that is potentially dangerous and may not work, you have to do more work to make it work so you will find yourself thinking more about it.
Finally it allows you do some *more* dynamic jumps than if variables were directly supported, for example you could go something like `<<jump {$bestFriend + "-date"}>>` or `<<jump {$bestFriend + "-leave"}` all relying on the interpolation to handle building up the node name.
That way you can reuse the `$bestFriend` variable in any place it is needed without having to track more things just to jump.

From an implementation perspective I guess the jump command would have to take in whatever parameter it gets and force cast it to a string which will always work unless it is null.
The last thing about this is I think we will need a clearer "you attempted a jump to a non-existent node" error message from Yarn Spinner to the rest of the game.
Regardless of the actual syntax chosen for jumping now that there is going to be an increased number of missed jumps (or likely increased number) we need a stronger and clearer "node X does not exist" messaging so the game can work out what to do.

**Comment by dogboydog** [comment]
I agree it should be consistent with other command syntax

**Comment by Haapavuo** [comment]
For our purposes I created a simple `<<jumpTo {$returnNode}>>` since jump did not accept variables.
