### ISSUE TITLE
.YarnProject fails import when inferring variable type as integer via increment

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnSpinner#338]
**What is the current behavior?**

When implicitly defining a variable through its usage a certain way, the .yarnproject will fail to import and cause various runtime errors.  The compile itself fails with a generic error that could also be improved.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Create a .yarn file with the following contents:
```
title: Bug3
---
<<set $akos_talkers = $akos_talkers + 1>>
===
```

![image](https://user-images.githubusercontent.com/143504/201503358-c95881e3-bc96-4613-9545-287123a1c316.png)

**What is the expected behavior?**

$akos_talkers should be detected as an integer, and the .yarnproject compiles

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2
  - Unity Version: 2021.3.10f1

**Other information**

**Comment by nefyodovve** [comment]
I think `declare` should help:

```
title: Bug3
---
<<declare $akos_talkers = 0 as int>>
<<set $akos_talkers = $akos_talkers + 1>>
===
```

**Comment by McJones** [comment]
There are two parts to this bug, the first is that the type inference isn't working correctly.
This is fixed in the WIP line groups branch which has a much more rigorous type system.
The second is it crashes the import at Unity, this is fixed in https://github.com/YarnSpinnerTool/YarnSpinner-Unity/commit/6d5054b993f9b77cf034885e60fd04eebc6d3225

Closing this now, thanks for finding it.
