### ISSUE TITLE
Window Store App Support

### ISSUE THREAD

**Issue by Hexalotl** [YarnSpinnerTool/YarnSpinner#42]
Currently when making a build for Windows Store apps, I get the following errors:

Reference Rewriter found some errors while running with command --
1. \- Error: method `System.Void System.IO.StreamReader::.ctor(System.String)` doesn't exist in target framework. It is referenced from YarnSpinner.dll at System.Void Yarn.Dialogue::LoadFile(System.String,System.Boolean,System.Boolean,System.String).
2. \- Error: method `System.Boolean System.Type::IsInstanceOfType(System.Object)` doesn't exist in target framework. It is referenced from YarnSpinner.dll at System.Void Yarn.Value::.ctor(System.Object).
3. \- Error: method `System.Reflection.Assembly System.Type::get_Assembly()` doesn't exist in target framework. It is referenced from YarnSpinner.dll at System.Collections.Generic.IEnumerable`1<System.Type> Yarn.Analysis.Context::get_defaultAnalyserClasses().
4. \- Error: method `System.Boolean System.Type::get_IsAbstract()` doesn't exist in target framework. It is referenced from YarnSpinner.dll at System.Collections.Generic.IEnumerable`1<System.Type> Yarn.Analysis.Context::get_defaultAnalyserClasses().

**Comment by desplesda** [comment]
Hmm!

Is this for Windows Phone, or Windows desktop?

**Comment by Dynameter** [comment]
This occurs when trying to make a build for Windows Store Apps, which can be downloaded through Microsoft's app store for tablets, phones, and even desktops. The problem with Windows Store Apps is that they don't support certain features very well such as reflection and certain IO operations. Unity itself offers support for some of the missing IO classes/functionality, but that would introduce a dependency to Unity. An option is to not have the IO functionality in Yarn since you can load the file through the Unity provided functionality and just load the contents of the file as a string through Yarn.

In addition, to build the library for Windows Store Apps, you usually need a portable class library project. Which means replacing the current YarnSpinner .csproj with a portable class library project or creating a new project just for Windows Store Apps.

I've fixed up these type of issues on a previous project and can help make the changes needed to get it working on WSA.

**Comment by desplesda** [comment]
Ok! I have zero experience with the Windows ecosystem haha, so if you'd like to submit a pill request, I'd really appreciate it! :)

**Comment by desplesda** [comment]
Closing, because the associated pull request #44/#45 were also closed.
