### ISSUE TITLE
Parse error with line feed inside options

### ISSUE THREAD

**Issue by madsbangh** [YarnSpinnerTool/YarnSpinner#72]
Having a line feed (\n) in the text inside an option (as shown in the example below) produces
a Yarn parse error:
"ParseException: In file Error Script: Error parsing node Start: Line 3:10: Expected OptionEnd, but found Text"

{
    "title": "Start",
    "tags": "",
    "body": "Testing.[[Error\nError|SomeNode]]",
    "position": {
        "x": 592,
        "y": 181
    },
    "colorID": 0
},

**Comment by bowlercaptain** [comment]
Reproduced. Is this in the yarn spec? This does cause this error, but feels like it's on the boundary of what logically works in the Yarn format. Definitely we should support arbitrary display text, but maybe this should be the responsibility of the user writing the UI handler? Writing "\n" in Yarn produces a "\\n" in the text file, which delivers a "\n" to the UI handler. At least as a stopgap, you could pass this to your UI and interpret it as a newline to display an option with a newline?
[newlinetest.zip](https://github.com/thesecretlab/YarnSpinner/files/966319/newlinetest.zip)

**Comment by desplesda** [comment]
Yeah, Yarn doesn't have any concept of escaped characters. Keeping in mind the fact that the primary goal of Yarn is to be a language for writers, I'm hesitant to include more features that we have to explain. This would be one of them.

@bowlercaptain, your comment about this possibly being the responsibility of the UI handler is making me think that some kind of API for intercepting and formatting the text that's delivered to the game might be useful.

However, getting back to the original post: we should define whether this is the expected behaviour or not. My feeling is that lines _should_ be allowed to go over multiple lines - I can't think of a good reason why they shouldn't, given that we've got defined syntax for where they start and end (`[[` and `]]`), which means there's no ambiguity for the parser.

I'm therefore marking this as a bug to be fixed.

**Comment by McJones** [comment]
Which the changes in 1.0 JSON is no longer supported so I am closing this issue.
