### ISSUE TITLE
Possibility of line tag collisions in LineAdder

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#80]
The LineAdder adds tags to user-visible content by generating a unique tag. It makes an effort to not create duplicates across the set of files it's handed to, but there are two ways that collisions can still happen:

* Tagging a file, and then separately tagging another; the second tagging operation doesn't know about any tags added in the first operation, and might create duplicates
* When tagging a file that's previously been tagged, the line adder doesn't read in any existing tags that are already present in the file, and might end up generating a duplicate.

**Comment by cdnDave** [comment]
Just an amendment to the second point. I think the line adder does read in existing tags in a given file before generating any new tags from that file. What it doesn't do is read existing tags in all files in the list of files to be tagged before tagging any file. Due to this it's possible for the line adder to assign a tag that's already in use by a file later in the list.

**Comment by McJones** [comment]
I believe this has been fixed so I am closing this issue.
If the issue reappears please open a new issue.
